---
- name: Nginx Web Server Setting Up
  hosts: all
  remote_user: ubuntu
  become: yes
  tasks:
  - name: Updating apt package list
    apt:
     update_cache: yes
  - name: Nginx installing
    apt:
     name: nginx
     state: latest
  - name: Nginx.service starting via systemd
    service:
     name: nginx
     state: restarted
     enabled: yes